config:
  info: system-dev-localhost
spring:
  profiles:
    active: dev
  datasource:
    name: db_system
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  config:
    location: classpath:mybatis/mybatis-config.xml
  mapper:
    locations: classpath:mapper/**/*.xml
logging:
  file: logs/system